#pragma config(Sensor, dgtl1,  EncoderToUse,   sensorRotation)
#pragma config(Motor,  port2,           frontRight,    tmotorNone, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorNone, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorNone, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	SensorValue[EncoderToUse] = 0;
	while(true)
	{


		//	if(vexRT[Btn5D] == 1)
		//{

		if(SensorValue[EncoderToUse] < 500)
		{

			//forward

			//shooting catapult
			motor[frontRight] = 100;
			motor[frontLeft] = 100;
			motor[backRight] = -100;
			motor[backLeft] =  -100;

			if(SensorValue[EncoderToUse] >=500)
			{
				motor[frontRight] = 0;
				motor[frontLeft] = 0;
				motor[backRight] = 0;
				motor[backLeft] =  0;
				wait1Msec(2000);
				SensorValue[EncoderToUse] = 0;
				if(SensorValue[EncoderToUse] < 500)
				{

					//backward
					motor[frontRight] = -100;
					motor[frontLeft] = -100;
					motor[backRight] = 100;
					motor[backLeft] =  100;
					wait1Msec(2000);
					if(SensorValue[EncoderToUse] >=500)
					{
						SensorValue[EncoderToUse] = 0;
						if(SensorValue[EncoderToUse] < 1000)
						{
							motor[frontRight] = 100;
							motor[frontLeft] = -100;
							motor[backRight] = 100;
							motor[backLeft] = -100;
						}
					}
				}
				else
				{
					break;
				}
			}
		}


		//move towards the platform
		//move left


		else
		{
		/*wait1Msec(100);
			motor[frontRight] = 60;
			motor[frontLeft] = -60;
			motor[backRight] = 60;
			motor[backLeft] = -60;
			wait1Msec(100);
			motor[frontRight] = 0;
			motor[frontLeft] = 0;
			motor[backRight] = 0;
			motor[backLeft] = 0;*/
		}

//	}

	}
}
